/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BackupData {
  'backedUpAt' : bigint,
  'exams' : Array<Exam>,
  'trialState' : [] | [TrialState],
  'userProfile' : [] | [UserProfile],
}
export interface DailyTask {
  'id' : bigint,
  'isCompleted' : boolean,
  'subjectName' : string,
  'scheduledDate' : bigint,
  'isRevision' : boolean,
  'examId' : bigint,
  'topicName' : string,
}
export interface DayProgress {
  'totalTasks' : bigint,
  'completedTasks' : bigint,
  'percentage' : bigint,
}
export interface Exam {
  'id' : bigint,
  'tasks' : Array<DailyTask>,
  'createdAt' : bigint,
  'setup' : ExamSetup,
}
export interface ExamSetup {
  'dailyHours' : bigint,
  'subjects' : Array<Subject>,
  'examDate' : bigint,
  'examName' : string,
}
export type PremiumFeature = { 'advanced_statistics' : null } |
  { 'advanced_focus_mode' : null } |
  { 'smart_study_insights' : null } |
  { 'cloud_backup' : null } |
  { 'customizable_themes' : null } |
  { 'ad_free_experience' : null } |
  { 'unlimited_study_plans' : null };
export interface ProgressData {
  'totalCompleted' : bigint,
  'studyStreak' : bigint,
  'totalPending' : bigint,
  'weeklyEntries' : Array<WeeklyProgressEntry>,
}
export interface Subject { 'name' : string, 'topics' : Array<string> }
export interface TrialState {
  'trialActive' : boolean,
  'trialUsed' : boolean,
  'trialStartTimestamp' : bigint,
}
export interface UserProfile {
  'userTier' : UserTier,
  'name' : string,
  'guestMode' : boolean,
  'deviceId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserTier = { 'trial' : null } |
  { 'premium' : null } |
  { 'free' : null };
export interface WeeklyProgressEntry {
  'totalTasks' : bigint,
  'completedTasks' : bigint,
  'dayLabel' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'backupUserData' : ActorMethod<[], undefined>,
  'checkFeatureAccess' : ActorMethod<
    [PremiumFeature],
    { 'accessGranted' : boolean }
  >,
  'checkGuestFeatureAccess' : ActorMethod<[string, PremiumFeature], boolean>,
  'createGuestProfile' : ActorMethod<[string, string], undefined>,
  'getAllExams' : ActorMethod<[], Array<Exam>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDayProgress' : ActorMethod<[bigint], DayProgress>,
  'getGuestExams' : ActorMethod<[string], Array<Exam>>,
  'getGuestProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getGuestStudyStreak' : ActorMethod<[string, bigint], bigint>,
  'getGuestTrialStatus' : ActorMethod<[string], boolean>,
  'getGuestWeeklyProgress' : ActorMethod<[string, bigint], ProgressData>,
  'getGuestWeeklyStats' : ActorMethod<
    [string],
    { 'streak' : bigint, 'totalTasks' : bigint, 'completedTasks' : bigint }
  >,
  'getLatestBackup' : ActorMethod<[], [] | [BackupData]>,
  /**
   * / Returns the premium status for the caller.
   */
  'getPremiumStatus' : ActorMethod<[], boolean>,
  'getStudyStreak' : ActorMethod<[bigint], bigint>,
  'getTodayGuestTasks' : ActorMethod<[string, bigint], Array<DailyTask>>,
  'getTodayTasks' : ActorMethod<[bigint], Array<DailyTask>>,
  'getTrialStatus' : ActorMethod<[], boolean>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyProgress' : ActorMethod<[bigint], ProgressData>,
  'getWeeklyStats' : ActorMethod<
    [],
    { 'streak' : bigint, 'totalTasks' : bigint, 'completedTasks' : bigint }
  >,
  'hasFeatureAccess' : ActorMethod<[PremiumFeature], boolean>,
  'hasTierAccess' : ActorMethod<[UserTier], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markGuestTaskComplete' : ActorMethod<[string, bigint, bigint], undefined>,
  'markGuestTaskIncomplete' : ActorMethod<[string, bigint, bigint], undefined>,
  'markTaskComplete' : ActorMethod<[bigint, bigint], undefined>,
  'markTaskIncomplete' : ActorMethod<[bigint, bigint], undefined>,
  'restoreUserData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startGuestTrial' : ActorMethod<[string], undefined>,
  'startTrial' : ActorMethod<[], undefined>,
  /**
   * / Stores the given premium status for the caller.
   */
  'storePremiumStatus' : ActorMethod<[boolean], undefined>,
  'submitExamSetup' : ActorMethod<[ExamSetup], bigint>,
  'submitGuestExamSetup' : ActorMethod<[string, ExamSetup], bigint>,
  'upgradeGuestToPremium' : ActorMethod<[string], undefined>,
  'upgradeToPremium' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];