/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PremiumFeature = IDL.Variant({
  'advanced_statistics' : IDL.Null,
  'advanced_focus_mode' : IDL.Null,
  'smart_study_insights' : IDL.Null,
  'cloud_backup' : IDL.Null,
  'customizable_themes' : IDL.Null,
  'ad_free_experience' : IDL.Null,
  'unlimited_study_plans' : IDL.Null,
});
export const DailyTask = IDL.Record({
  'id' : IDL.Nat,
  'isCompleted' : IDL.Bool,
  'subjectName' : IDL.Text,
  'scheduledDate' : IDL.Int,
  'isRevision' : IDL.Bool,
  'examId' : IDL.Nat,
  'topicName' : IDL.Text,
});
export const Subject = IDL.Record({
  'name' : IDL.Text,
  'topics' : IDL.Vec(IDL.Text),
});
export const ExamSetup = IDL.Record({
  'dailyHours' : IDL.Nat,
  'subjects' : IDL.Vec(Subject),
  'examDate' : IDL.Int,
  'examName' : IDL.Text,
});
export const Exam = IDL.Record({
  'id' : IDL.Nat,
  'tasks' : IDL.Vec(DailyTask),
  'createdAt' : IDL.Int,
  'setup' : ExamSetup,
});
export const UserTier = IDL.Variant({
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userTier' : UserTier,
  'name' : IDL.Text,
  'guestMode' : IDL.Bool,
  'deviceId' : IDL.Opt(IDL.Text),
});
export const DayProgress = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const WeeklyProgressEntry = IDL.Record({
  'totalTasks' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'dayLabel' : IDL.Text,
});
export const ProgressData = IDL.Record({
  'totalCompleted' : IDL.Nat,
  'studyStreak' : IDL.Nat,
  'totalPending' : IDL.Nat,
  'weeklyEntries' : IDL.Vec(WeeklyProgressEntry),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkFeatureAccess' : IDL.Func(
      [PremiumFeature],
      [IDL.Record({ 'accessGranted' : IDL.Bool })],
      ['query'],
    ),
  'createGuestProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDayProgress' : IDL.Func([IDL.Nat], [DayProgress], ['query']),
  'getGuestExams' : IDL.Func([IDL.Text], [IDL.Vec(Exam)], ['query']),
  'getGuestProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'getGuestStudyStreak' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
  'getGuestWeeklyProgress' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [ProgressData],
      ['query'],
    ),
  'getStudyStreak' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getTodayGuestTasks' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(DailyTask)],
      ['query'],
    ),
  'getTodayTasks' : IDL.Func([IDL.Nat], [IDL.Vec(DailyTask)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyProgress' : IDL.Func([IDL.Nat], [ProgressData], ['query']),
  'hasFeatureAccess' : IDL.Func([PremiumFeature], [IDL.Bool], ['query']),
  'hasTierAccess' : IDL.Func([UserTier], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markGuestTaskComplete' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'markGuestTaskIncomplete' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'markTaskComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'markTaskIncomplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitExamSetup' : IDL.Func([ExamSetup], [IDL.Nat], []),
  'submitGuestExamSetup' : IDL.Func([IDL.Text, ExamSetup], [IDL.Nat], []),
  'upgradeToPremium' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PremiumFeature = IDL.Variant({
    'advanced_statistics' : IDL.Null,
    'advanced_focus_mode' : IDL.Null,
    'smart_study_insights' : IDL.Null,
    'cloud_backup' : IDL.Null,
    'customizable_themes' : IDL.Null,
    'ad_free_experience' : IDL.Null,
    'unlimited_study_plans' : IDL.Null,
  });
  const DailyTask = IDL.Record({
    'id' : IDL.Nat,
    'isCompleted' : IDL.Bool,
    'subjectName' : IDL.Text,
    'scheduledDate' : IDL.Int,
    'isRevision' : IDL.Bool,
    'examId' : IDL.Nat,
    'topicName' : IDL.Text,
  });
  const Subject = IDL.Record({
    'name' : IDL.Text,
    'topics' : IDL.Vec(IDL.Text),
  });
  const ExamSetup = IDL.Record({
    'dailyHours' : IDL.Nat,
    'subjects' : IDL.Vec(Subject),
    'examDate' : IDL.Int,
    'examName' : IDL.Text,
  });
  const Exam = IDL.Record({
    'id' : IDL.Nat,
    'tasks' : IDL.Vec(DailyTask),
    'createdAt' : IDL.Int,
    'setup' : ExamSetup,
  });
  const UserTier = IDL.Variant({ 'premium' : IDL.Null, 'free' : IDL.Null });
  const UserProfile = IDL.Record({
    'userTier' : UserTier,
    'name' : IDL.Text,
    'guestMode' : IDL.Bool,
    'deviceId' : IDL.Opt(IDL.Text),
  });
  const DayProgress = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const WeeklyProgressEntry = IDL.Record({
    'totalTasks' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'dayLabel' : IDL.Text,
  });
  const ProgressData = IDL.Record({
    'totalCompleted' : IDL.Nat,
    'studyStreak' : IDL.Nat,
    'totalPending' : IDL.Nat,
    'weeklyEntries' : IDL.Vec(WeeklyProgressEntry),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkFeatureAccess' : IDL.Func(
        [PremiumFeature],
        [IDL.Record({ 'accessGranted' : IDL.Bool })],
        ['query'],
      ),
    'createGuestProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDayProgress' : IDL.Func([IDL.Nat], [DayProgress], ['query']),
    'getGuestExams' : IDL.Func([IDL.Text], [IDL.Vec(Exam)], ['query']),
    'getGuestProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'getGuestStudyStreak' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
    'getGuestWeeklyProgress' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [ProgressData],
        ['query'],
      ),
    'getStudyStreak' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getTodayGuestTasks' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(DailyTask)],
        ['query'],
      ),
    'getTodayTasks' : IDL.Func([IDL.Nat], [IDL.Vec(DailyTask)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyProgress' : IDL.Func([IDL.Nat], [ProgressData], ['query']),
    'hasFeatureAccess' : IDL.Func([PremiumFeature], [IDL.Bool], ['query']),
    'hasTierAccess' : IDL.Func([UserTier], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markGuestTaskComplete' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'markGuestTaskIncomplete' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'markTaskComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'markTaskIncomplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitExamSetup' : IDL.Func([ExamSetup], [IDL.Nat], []),
    'submitGuestExamSetup' : IDL.Func([IDL.Text, ExamSetup], [IDL.Nat], []),
    'upgradeToPremium' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };